### ISSUE TITLE
Add responsiveness to the site

### ISSUE THREAD

**Issue by sam-shervin** [ComputerSocietyVITC/hackhub-24#8]
- add responsiveness to mobile devices as well as tablet PCs.

**Comment by sam-shervin** [comment]
@Calciumcarbonate321 once you're done making it responsive, PR dev branch to main branch

**Comment by Calciumcarbonate321** [comment]
Once I am done I will do a PR Sam

**Comment by sam-shervin** [comment]
Responsiveness done
